name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: website-lovable-shift/package-lock.json
    
    - name: Install dependencies
      run: |
        cd website-lovable-shift
        npm ci --production=false
    
    - name: Run tests
      run: |
        cd website-lovable-shift
        npm run check:react-imports
        npm run text:check || true  # Allow text check to fail on first run
    
    - name: Build application
      run: |
        cd website-lovable-shift
        npm run build
        
    - name: Deploy to production
      run: |
        # Copy built files to web directory
        sudo rsync -av --delete website-lovable-shift/dist/ /srv/www/seaview-site/
        
        # Copy proxy server files
        sudo rsync -av --delete ical-proxy-server/ /srv/apps/seaview-proxy/
        
        # Install proxy dependencies
        cd /srv/apps/seaview-proxy
        sudo npm ci --production
        
        # Restart proxy server
        sudo pm2 restart ecosystem.config.js --update-env
        sudo pm2 save
        
    - name: Verify deployment
      run: |
        # Check if website is accessible
        curl -f http://localhost/ || exit 1
        
        # Check if proxy is running
        curl -f http://localhost:3001/health || exit 1 